#!/bin/bash
# Install GoLinx as a systemd service on Linux.
# Usage:  curl -fsSL https://raw.githubusercontent.com/staceyw/GoLinx/main/scripts/install-service.sh | sudo bash
set -e

REPO="staceyw/GoLinx"
BASE_URL="https://github.com/$REPO/releases/latest/download"
BIN_PATH="/usr/local/bin/golinx"
SERVICE_FILE="/etc/systemd/system/golinx.service"

# --- Must be root ------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
  echo "Error: This script must be run as root (use sudo)."
  exit 1
fi

# --- Detect architecture -----------------------------------------------------

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64)  ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  *)             echo "Error: Unsupported architecture: $ARCH"; exit 1 ;;
esac

BINARY="golinx-linux-${ARCH}"

# --- Helper for reading input (works with curl | sudo bash) ------------------

prompt() {
  printf "%s" "$1"
  if [ -t 0 ]; then
    read -r REPLY
  else
    read -r REPLY < /dev/tty
  fi
}

# --- Gather configuration ----------------------------------------------------

echo ""
echo "GoLinx Service Installer"
echo "========================"
echo ""

# Data directory
REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo root)}"
DEFAULT_DIR="/home/${REAL_USER}/golinx"

prompt "Data directory (config + database) [$DEFAULT_DIR]: "
DATA_DIR="${REPLY:-$DEFAULT_DIR}"

if [ -d "$DATA_DIR" ]; then
  echo "  OK: $DATA_DIR exists."
elif [ -e "$DATA_DIR" ]; then
  echo "Error: $DATA_DIR exists but is not a directory."
  exit 1
else
  prompt "  $DATA_DIR does not exist. Create it? [Y/n] "
  case "$REPLY" in
    [nN]*) echo "Aborted."; exit 1 ;;
  esac
  mkdir -p "$DATA_DIR"
  echo "  Created: $DATA_DIR"
fi

# Listener
prompt "Listener URI [http://:80]: "
LISTENER="${REPLY:-http://:80}"
LISTENER2=""

# Tailscale hostname (only if ts+* listener)
TS_HOSTNAME=""
case "$LISTENER" in
  ts+https*)
    prompt "Tailscale hostname [go]: "
    TS_HOSTNAME="${REPLY:-go}"
    echo "  Recommended: add ts+http://:80 so go/link works (bare hostnames need HTTP)."
    prompt "  Add ts+http://:80 listener? [Y/n] "
    case "$REPLY" in
      [nN]*) ;;
      *)     LISTENER2="ts+http://:80" ;;
    esac
    ;;
  ts+http*)
    prompt "Tailscale hostname [go]: "
    TS_HOSTNAME="${REPLY:-go}"
    ;;
  https*)
    echo "  Recommended: add http://:80 so go/link works (bare hostnames need HTTP)."
    prompt "  Add http://:80 listener? [Y/n] "
    case "$REPLY" in
      [nN]*) ;;
      *)     LISTENER2="http://:80" ;;
    esac
    ;;
esac

# Run-as user
DETECTED_USER=$(stat -c '%U' "$DATA_DIR" 2>/dev/null || stat -f '%Su' "$DATA_DIR" 2>/dev/null || echo "$REAL_USER")
prompt "Run service as user [$DETECTED_USER]: "
RUN_USER="${REPLY:-$DETECTED_USER}"

if ! id "$RUN_USER" >/dev/null 2>&1; then
  echo "Error: User $RUN_USER does not exist."
  exit 1
fi

# --- Confirm ------------------------------------------------------------------

echo ""
echo "Configuration:"
echo "  Binary:      $BIN_PATH"
echo "  Data dir:    $DATA_DIR"
echo "  Listener:    $LISTENER"
if [ -n "$LISTENER2" ]; then
  echo "               $LISTENER2"
fi
if [ -n "$TS_HOSTNAME" ]; then
  echo "  TS hostname: $TS_HOSTNAME"
fi
echo "  Run as:      $RUN_USER"
echo ""
prompt "Install and start service? [Y/n] "
case "$REPLY" in
  [nN]*) echo "Aborted."; exit 0 ;;
esac

# --- Download binary ----------------------------------------------------------

echo ""
echo "Downloading $BINARY ..."
if command -v curl >/dev/null 2>&1; then
  curl -fsSL -o "$BIN_PATH" "${BASE_URL}/${BINARY}"
elif command -v wget >/dev/null 2>&1; then
  wget -q -O "$BIN_PATH" "${BASE_URL}/${BINARY}"
else
  echo "Error: Neither curl nor wget found."
  exit 1
fi
chmod +x "$BIN_PATH"
echo "  Installed: $BIN_PATH"

# --- Generate config if not present -------------------------------------------

CONFIG_FILE="${DATA_DIR}/golinx.toml"
if [ -f "$CONFIG_FILE" ]; then
  echo "  Config exists: $CONFIG_FILE (keeping existing)"
else
  echo "  Generating: $CONFIG_FILE"
  if [ -n "$LISTENER2" ]; then
    cat > "$CONFIG_FILE" <<TOML
# GoLinx configuration (generated by install-service.sh)

listen = [
  "$LISTENER",
  "$LISTENER2",
]
TOML
  else
    cat > "$CONFIG_FILE" <<TOML
# GoLinx configuration (generated by install-service.sh)

listen = [
  "$LISTENER",
]
TOML
  fi

  if [ -n "$TS_HOSTNAME" ]; then
    echo "ts-hostname = \"$TS_HOSTNAME\"" >> "$CONFIG_FILE"
  fi

  chown "$RUN_USER" "$CONFIG_FILE"
fi

# Ensure data dir is owned by run user
chown "$RUN_USER" "$DATA_DIR"

# --- Create systemd service ---------------------------------------------------

echo "Creating systemd service ..."

# Build ExecStart — just the binary, config file in WorkingDirectory handles the rest
EXEC_START="$BIN_PATH"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=GoLinx - URL Shortener & People Directory
After=network.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$DATA_DIR
ExecStart=$EXEC_START
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

echo "  Created: $SERVICE_FILE"

# --- Enable and start ---------------------------------------------------------

systemctl daemon-reload
systemctl enable golinx
systemctl start golinx

echo ""
echo "Done! GoLinx is running."
echo ""
echo "  Status:   sudo systemctl status golinx"
echo "  Logs:     journalctl -u golinx -f"
echo "  Stop:     sudo systemctl stop golinx"
echo "  Restart:  sudo systemctl restart golinx"
echo ""
echo "Config: $CONFIG_FILE"
echo "To change settings, edit the config file then:"
echo "  sudo systemctl restart golinx"
echo ""
